site_name: Ye Jiaqi Site
pages:
  - 主页: 'index.md'
  - 架构相关:
    - 设计模式:
        - MVC解读: 'posts/architecture/design-pattern/MVC解读.md'
  - 算法:
    - 证明二分查找优于三分查找、四分查找: 'posts/algorithmn/prove-binary-search-is-better.md'
  - 大前端:
    - angular:
        - AngularJS源代码阅读(1) —— angularjs 沉思: 'posts/front-end/angular/AngularJS源代码阅读(1).md'
        - AngularJS源代码阅读(2) —— 项目结构: 'posts/front-end/angular/AngularJS源代码阅读(2).md'
    - javasctipt:
        - JS原型链什么鬼: 'posts/front-end/javascript/JS原型链什么鬼.md'
        - JS闭包什么鬼: 'posts/front-end/javascript/JS闭包什么鬼.md'
        - JS的this什么鬼: 'posts/front-end/javascript/JS的this什么鬼.md'
        - JS常见大坑: 'posts/front-end/javascript/JS常见大坑.md'
        - 一道JS神面试题: 'posts/front-end/javascript/一道JS神面试题.md'
    - 范式:
        - 函数式编程中的纯函数: 'posts/front-end/paradigms/pure-function.md'
    - 调研:
        - antd生态下的react组件管理: 'posts/front-end/survey/ant-design-componets-management.md'
    - 分享会:
        - 吴家荣大佬-React技术生态和服务端渲染: 'posts/front-end/share/React技术生态和服务端渲染.md'
  - 旧文档:
    - 数图作业:
        - Quantization and Scaling: 'posts/old/Quantization-and-Scaling.md'
        - Filtering1: 'posts/old/Filtering(1).md'
        - Filtering2: 'posts/old/Filtering(2).md'
        - Histogram Equalization: 'posts/old/Histogram-Equalization.md'
        - Fourier Transformation: 'posts/old/Fourier-Transformation.md'
        - Stero Matching: 'posts/old/stero-matching.md'
    - 以前的项目:
        - YOJ: 'posts/old/YOJ.md'
        - Simple Sinew: 'posts/old/simple-sinew.md'
        - Floater: 'posts/old/Floater.md'
        - Asentence: 'posts/old/Asentence.md'
    - 出过的习题:
        - 程序流程图和伪代码: 'posts/old/FlowChart-and-PseudoCode.md'
        - 内存错误总结: 'posts/old/Memory-Error-Summary-in-c++.md'
        - 简单链表: 'posts/old/SimpleList.md'
    - 面经:
        - 腾讯实习面试: 'posts/old/Tencent-interview.md'
        - 华为实习面试: 'posts/old/Huawei-interview.md'
        - 网易实习面试: 'posts/old/Netease-interview.md'
theme: 'material'
markdown_extensions:
  - admonition
  - markdown.extensions.toc:
      permalink: true
      separator: '_'
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      base_repo_url: https://github.com/facelessuser/pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.plainhtml:
      strip_attributes: ''
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

extra:
  # palette:
    # primary: blue
    # accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: github
      link: https://github.com/ghostbody

extra-css:
    - /assets/css/style.css

extra_javascript:
     - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'